import type { Lesson, Module, Path, SlideKind } from "./types";
import { inputs } from "./inputs";
const slide = (id: string, title: string, subtitle: string, points: string[], takeaway: string, source = "intro", kind: SlideKind = "concept", focus?: string): Lesson =>
  ({ id, title, subtitle, points, takeaway, source, kind, focus, note: "Ask learners to predict the result before revealing it. " + takeaway });
const quiz = (id: string, title: string, question: string, options: string[], answer: number, explanation: string, source = "intro"): Lesson =>
  ({ ...slide(id, title, "Pause, predict, then check your understanding.", [], explanation, source, "quiz"), quiz: { question, options, answer, explanation } });
export const modules: Module[] = [
  { id: "welcome", label: "00", title: "Start here", description: "Your workshop, one step at a time", path: "shared", minutes: 4, lessons: [
    slide("welcome", "Give your robot a point of reference.", "Learn AprilTags. Set up a camera. Make sense of what your robot sees.", ["Explore the shared foundations, then choose Webcam, Limelight 3A, or both.", "Learn through diagrams, real API examples, and a hands-on virtual field.", "Finish by using camera measurements to guide bounded robot motion."], "Start with a reliable measurement. Build robot behavior on top of it.", "intro", "tag"),
    slide("outcomes", "From a printed tag to a robot decision.", "The workshop follows the same path as your data.", ["Recognize the tag family, ID, physical size, and pose.", "Configure a camera and validate its results.", "Read Java, inspect telemetry, and tune a safe turn-to-target controller."], "Camera → detection → validation → telemetry → control.", "portal", "flow"),
    slide("equipment", "Bring the right pieces.", "You can complete the browser lessons without hardware.", ["For a physical lab: Control Hub, Driver Station, a configured robot, and a printed 36h11 tag of measured size.", "Webcam path: a supported UVC webcam and a secure USB connection.", "Limelight path: a Limelight 3A, USB-C to USB-A cable, laptop, and rigid mounting hardware."], "Measure the tag's black border before trusting a distance estimate.", "quick", "setup"),
    slide("orientation", "Make the lab your teaching companion.", "Use the course outline to jump, or follow the lessons in order.", ["Next marks reading lessons complete. Quizzes and challenges require a successful answer or result.", "Open the lab alongside any lesson. Drag the robot or tags, or use the labeled position controls.", "Use ← / → to move between lessons. Presenter mode enlarges the lesson and reveals facilitator notes."], "Progress stays on this browser. Reset it from the course outline.", "intro", "flow"),
    slide("limits", "An explanation you can experiment with.", "The field is a deterministic teaching model.", ["There is no real camera capture, Java runtime, Android service, or robot connection.", "Noise, image quality, latency, and motor response illustrate cause and effect; they are not hardware benchmarks.", "The movable 141-inch practice field uses example tags and positions. Validate season maps and printed sizes separately."], "Use this lab to understand behavior, then validate code and tuning on hardware.", "intro"),
  ] },
  { id: "foundations", label: "01", title: "Meet the AprilTag", description: "IDs, size, pose, and reference frames", path: "shared", minutes: 12, lessons: [
    slide("what-tag", "A small marker. A useful reference.", "An AprilTag is a visual fiducial: a recognizable pattern with a numeric ID.", ["A detector recognizes the black-and-white pattern in an image.", "The encoded number identifies the tag; it does not store a field location.", "With physical size and camera calibration, software can estimate the tag's position and orientation."], "ID answers “which tag?” Pose answers “where, relative to what?”", "intro", "tag"),
    slide("anatomy", "Read the pattern, not the paper.", "Three parts make the marker detectable.", ["The white margin separates the tag from its surroundings.", "The black border defines the square used for physical size.", "The interior cells encode an ID within a family; FTC uses 36h11."], "Measure across the outside edge of the black border, excluding the white margin.", "intro", "tag"),
    slide("metadata", "ID, metadata, and pose are different.", "A detection can have an ID even when the tag is not in your library.", ["ID: the number decoded from the image.", "Metadata: known size, name, and optionally field location from a tag library.", "Pose: the estimated position and orientation relative to the camera."], "Check metadata before using the pose in the supplied drive-to-tag sample.", "library", "flow"),
    slide("tag-size", "Wrong size means wrong scale.", "Pose estimation needs a physical measurement.", ["This virtual lab uses a measured practice size of 50.8 mm (2 inches).", "If software assumes a tag twice as large, its estimated distance grows by the same factor.", "Use the actual printed size or the applicable season's official specification. 165.1 mm is not universal for FTC."], "Open the lab and double Marker size. Compare estimated range with ground truth.", "intro", "challenge", "size"),
    slide("frames", "Every pose belongs to a frame.", "Always ask: position of what, measured from where?", ["FTC camera-relative axes: +X right, +Y forward, +Z up.", "Bearing is positive to the camera's left; a horizontal target angle is not a distance.", "Robot-center and field coordinates require the camera mounting transform and a known tag map."], "The lab labels its field axes and heading explicitly: 0° along +X, 90° along +Y.", "pose", "axes"),
    slide("accuracy", "A detection is an estimate.", "A clear, large tag gives the estimator more information.", ["Blur, glare, poor light, or an edge-on tag can cause missed frames.", "Calibration must match the actual camera and resolution.", "Increase resolution for distant detail; consider the cost in frame rate and bandwidth."], "Tune from a clear stationary image before testing motion.", "intro"),
    slide("visibility", "Find the edge of what the camera sees.", "A tag can exist on the field and still be invisible.", ["Start the lab, then move the tag beyond the camera's field of view.", "Rotate the robot until the tag returns to the camera preview.", "Observe how result validity changes independently of the tag's existence."], "Challenge: get a valid result with tag 20 visible.", "intro", "challenge", "visible"),
    quiz("foundation-check", "Check your foundations", "A camera decodes ID 20, but the tag is absent from its library. What do you know?", ["Its exact field location", "Its ID, but not necessarily a usable metric pose", "Its distance from the robot center"], 1, "Decoding an ID and estimating a scaled pose are separate steps. Metadata and calibration supply the missing information.", "library"),
  ] },
  { id: "paths", label: "02", title: "Choose your camera", description: "Two paths to the same objective", path: "shared", minutes: 6, lessons: [
    slide("compare", "Two cameras. Two processing paths.", "Both can detect AprilTags, but they do the work in different places.", ["A webcam sends image frames to the Control Hub; VisionPortal manages the stream and AprilTagProcessor analyzes it.", "Limelight runs its pipeline on the smart camera; your OpMode polls result objects.", "Choose either track above, or keep Both to learn how the APIs compare."], "The processing location changes setup and APIs. The need to validate results stays the same.", "portal", "compare"),
    slide("choose", "Choose around the robot's task.", "Start with the measurement your team needs.", ["A webcam suits teams working directly with FTC processors and willing to tune Control Hub resource use.", "Limelight provides a dedicated processor, a browser setup UI, and built-in localization workflows.", "Consider available hardware, CPU and USB load, team experience, and whether you need simple centering or field localization. Compare current vendor prices separately."], "You do not need full field localization just to center on a visible tag.", "java", "compare"),
    quiz("path-check", "Follow the pixels", "In the webcam path, which component analyzes frames for AprilTags?", ["VisionPortal by itself", "AprilTagProcessor attached to VisionPortal", "Limelight3A"], 1, "VisionPortal manages the stream. The attached AprilTagProcessor performs AprilTag analysis.", "processor"),
  ] },
  { id: "webcam-setup", label: "03A", title: "Set up VisionPortal", description: "Camera, processor, and stream", path: "webcam", minutes: 18, lessons: [
    slide("webcam-wire", "Connect and name the webcam.", "Your Java hardware name must match Robot Configuration exactly.", ["Connect a supported USB webcam to the Control Hub and secure the cable.", "Scan in Robot Configuration, assign Webcam 1, save, and activate the configuration.", "Use hardwareMap.get(WebcamName.class, \"Webcam 1\") in the OpMode."], "“Webcam 1” and “webcam 1” are different names.", "init", "setup"),
    slide("processor", "Give each component one job.", "A camera captures. A processor analyzes. A portal manages.", ["AprilTagProcessor produces a list of AprilTagDetection objects.", "VisionPortal opens the camera and delivers frames to attached processors.", "A portal can have multiple processors; each evaluates frames independently."], "Creating the processor does not open a camera.", "processor", "flow"),
    slide("builders", "Build a processor, then a portal.", "Use defaults first; use Builders when you need settings.", ["AprilTagProcessor.easyCreateWithDefaults() is the short path.", "new AprilTagProcessor.Builder().build() makes customization explicit.", "VisionPortal.easyCreateWithDefaults(camera, aprilTag) or a Builder connects camera and processor."], "Initialize before waitForStart(); vision can run during INIT.", "init", "code", "webcam:processor"),
    slide("portal-builder", "Connect the camera to the processor.", "Builder calls describe the portal before build() opens it.", [".setCamera(...) selects the source; .addProcessor(aprilTag) attaches and enables detection.", ".setCameraResolution(...) needs calibration for that camera/resolution pair.", ".setStreamFormat(...) chooses YUY2 or MJPEG; .build() creates the portal."], "Open the code walkthrough and trace the camera → processor relationship.", "init", "code", "webcam:portal"),
    slide("previews", "Preview is a view of the stream.", "Seeing pixels and running detection are related but separate.", ["Driver Station Camera Stream lets you inspect what the robot camera sees.", "LiveView is the Robot Controller preview, with optional detection annotations.", "Turning off LiveView can save resources without necessarily disabling the processor."], "Use the preview to diagnose image quality before changing robot control.", "bandwidth"),
    slide("camera-state", "Wait until the camera is ready.", "Camera startup is asynchronous.", ["The portal progresses through opening and starting-stream states before STREAMING.", "The supplied sample waits for STREAMING before setting manual exposure and gain.", "Always let isStopRequested() break a wait; unsupported camera controls must be handled."], "A configured camera is not necessarily streaming yet.", "controls", "flow"),
    slide("camera-controls", "Collect enough light without blur.", "Camera control support and ranges differ by webcam.", ["Exposure changes the light collection time; gain amplifies the resulting signal.", "Focus and white balance can improve consistency when the camera supports them.", "The pasted sample's 6 ms exposure and gain 250 are example tuning values, not universal defaults."], "Use ConceptAprilTagOptimizeExposure to find settings for your camera and venue.", "controls"),
    slide("resources", "Keep the Control Hub responsive.", "Vision shares CPU and USB capacity with the rest of the robot.", ["MJPEG can reduce USB bandwidth compared with YUY2; test decoding cost and image quality.", "Disable unused processors, stop/resume streaming, or close the portal when appropriate.", "Higher resolution and multiple cameras need careful testing. Decimation can trade detection range for speed."], "Measure frame rate and robot-loop performance together.", "bandwidth", "flow"),
    slide("portal-challenge", "Build your first vision pipeline.", "Put three initialization steps in the right order.", ["Create AprilTagProcessor.", "Select Webcam 1 and attach the processor.", "Build VisionPortal, then inspect detections."], "Challenge: choose a processor, attach it, and start the camera in the assembly activity.", "init", "challenge", "assembly"),
  ] },
  { id: "limelight-setup", label: "03B", title: "Set up Limelight 3A", description: "Mount, connect, configure", path: "limelight", minutes: 12, lessons: [
    slide("ll-hardware", "A camera with its own processor.", "Limelight 3A runs LimelightOS and a browser-based configuration interface.", ["The 3A uses USB-C; it has no RJ45 Ethernet socket and no built-in illumination.", "Use a USB-C to USB-A data cable. Limelight and REV specify the Control Hub's blue USB 3.0 port.", "The green status light indicates detection activity; it does not prove your OpMode is reading results."], "Limelight processes images on the camera and sends data to your robot.", "quick", "setup"),
    slide("ll-mount", "Mount rigidly. Measure carefully.", "Moving camera mounts invalidate the geometry you configured.", ["Use at least two suitable M3/M4 screws in supported threaded holes.", "Keep the tag in view through the movement you intend to automate.", "Measure translation and orientation from robot center to the camera lens; enter them for 3D localization."], "A camera mounted 0.2 m forward is not at robot center.", "quick", "axes"),
    slide("ll-interface", "Open the Limelight interface.", "Configure on a laptop before reading results on the robot.", ["Connect the 3A to the laptop by USB and wait for startup.", "Use limelight.local:5801 or find the device in Limelight Hardware Manager.", "Set the FTC team number, restart the vision client as documented, then configure a pipeline."], "If the hostname fails, use Hardware Manager to discover the actual device.", "quick", "setup"),
    slide("ll-update", "Update deliberately.", "Flashing LimelightOS is a maintenance step, not routine pipeline editing.", ["Back up pipelines and scripts before an OS update; flashing can erase them.", "Follow the current 3A Quick-Start for your operating system.", "Record the OS version used in the workshop. Screenshots and control labels may differ."], "Do not copy old flashing commands without checking the current instructions.", "quick", "setup"),
    slide("ll-register", "Give the robot a hardware name.", "The 3A appears as an Ethernet Device through its USB connection.", ["Connect the 3A to the Control Hub USB 3.0 port.", "Driver Station → Configure Robot → Scan → Ethernet Device.", "Name the device limelight, save and activate the configuration, then use exactly that name in Java."], "hardwareMap gets a configured device; it does not discover it by guessing a name.", "quick", "code", "limelight:hardware"),
    slide("ll-first-result", "Get one reliable target first.", "Use a simple single-tag pipeline before adding localization.", ["Choose a slot, set AprilTags, select 36h11, and enter measured marker size.", "Start with an unobstructed tag and tune exposure until it is detected consistently.", "Then add the desired ID filter and verify the crosshair follows that tag."], "Challenge: start the lab and accept only tag 20.", "tracking", "challenge", "filter"),
    quiz("ll-setup-check", "Check the setup chain", "Your OpMode uses pipelineSwitch(8). What must be true?", ["Slot 8 must already be configured for the intended task", "ID 8 must be visible", "The camera must be named pipeline8"], 0, "Pipeline indices select saved processing configurations. They are unrelated to tag IDs.", "java"),
  ] },
  { id: "limelight-ui", label: "04", title: "Inside LimelightOS", description: "Learn what each input changes", path: "limelight", minutes: 25, lessons: inputs.map(i =>
    slide("ui-" + i.id, i.label, i.meaning, [i.effect, "Watch for: " + i.mistake], "Adjust this setting in the lab and explain the change before moving on.", i.source, "ui", i.id)
  ) },
  { id: "measurements", label: "05", title: "Read the results", description: "Angles, range, validity, and frames", path: "shared", minutes: 12, lessons: [
    slide("result-lifecycle", "A result is a snapshot of a frame.", "There is time between capture and the robot's decision.", ["The camera captures, the pipeline processes, and your OpMode reads a result.", "Check existence, validity, target ID, and freshness before commanding a motor.", "Polling faster does not create more camera frames."], "A previously valid result can be stale.", "java", "flow"),
    slide("angles", "Left and right are angles.", "Limelight tx and ty are offsets in degrees.", ["tx is the horizontal offset from the configured crosshair; positive is to the right.", "ty is vertical offset; positive is above the crosshair.", "getTxNC()/getTyNC() instead reference the camera's principal pixel. The lab uses a centered crosshair."], "Turn the robot and watch tx approach zero. No distance unit belongs on tx.", "java", "challenge", "angles"),
    slide("area-latency", "Area and latency tell different stories.", "ta is image coverage. Latency is elapsed time.", ["ta is a percentage of the image; a closer, larger, or more front-facing tag typically fills more pixels.", "Capture and pipeline latency have distinct meanings. Their sum is a useful processing-delay estimate, not a complete transport-age guarantee.", "The age/staleness of the result matters when motion is rapid."], "The lab's FPS, quality, and delay are illustrative, not Limelight benchmarks.", "java"),
    slide("webcam-values", "Read the detection, then its pose.", "A webcam returns a list, not one universal target.", ["id identifies the tag. center is a pixel location. metadata supplies known tag information.", "ftcPose.range is planar camera-to-tag range; bearing is the horizontal angle, positive left.", "Elevation describes up/down direction. Yaw, pitch, and roll describe tag orientation, not centering errors."], "Choose a tag explicitly and check metadata before using ftcPose.", "pose", "axes"),
    slide("field-pose", "Field pose needs more information.", "Camera-relative target position is only the first transformation.", ["Known tag positions provide the field reference.", "Camera mount translation and rotation relate the lens to robot center.", "MegaTag2 also uses robot orientation input. Verify the IMU frame, sign, and field map before fusing pose."], "Open the frame inspector to compare target-in-camera with robot-in-field.", "java", "ui", "map"),
    quiz("measure-check", "Choose the right measurement", "The robot should rotate until a tag is centered. Which webcam value is the direct heading error?", ["ftcPose.yaw", "ftcPose.bearing", "The tag's numeric ID"], 1, "Bearing is the direction to the tag. Yaw describes the tag face orientation and can stay nonzero while the tag is centered.", "pose"),
  ] },
  { id: "limelight-code", label: "06", title: "Read Limelight Java", description: "Follow the OpMode, line by line", path: "limelight", minutes: 18, lessons: [
    ["hardware", "Get the Limelight object", "Limelight3A is the device type; limelight is the Java reference. hardwareMap.get matches the configured device name."],
    ["poll", "Choose a polling cadence", "setPollRateHz controls how often the SDK requests results. telemetry cadence controls how often data is sent to Driver Station."],
    ["pipeline", "Select the saved pipeline", "pipelineSwitch(0) requests slot 0 asynchronously. Verify the pipeline index in returned results when switching."],
    ["start", "Start polling for results", "start() begins SDK result polling. It is separate from the Driver Station Start button."],
    ["wait", "Wait for the driver", "waitForStart() holds the OpMode until Start. Initialization belongs before this call."],
    ["loop", "Keep the OpMode responsive", "opModeIsActive() repeats the loop while running. Keep processing brief and allow Stop to take effect."],
    ["result", "Read the latest result", "LLResult contains the most recently available data; it may be null or older than your last loop."],
    ["valid", "Check existence and validity", "&& short-circuits: result.isValid() runs only after the non-null check. Freshness is a separate check."],
    ["tx", "Read angles, area, and latency", "getTx and getTy report degrees; getTa reports image percentage. Capture and targeting latency are milliseconds."],
    ["fiducials", "Inspect individual tag IDs", "getFiducialResults() exposes per-tag detections. Base tx/ty can be controlled by sorting or grouping."],
    ["telemetry", "Publish what you measured", "addData stages the values; telemetry.update() sends the current display to Driver Station."],
    ["stop", "Always release resources", "The finally block calls stop() even when initialization or execution exits early."],
  ].map(([focus, title, subtitle]) => slide("ll-code-" + focus, title, subtitle, ["Select any highlighted line to open its explanation.", "Use the walkthrough step controls to follow execution and preview its effect in the lab."], subtitle, "java", "code", "limelight:" + focus)) },
  { id: "webcam-code", label: "07", title: "Read VisionPortal Java", description: "Build, detect, filter, and clean up", path: "webcam", minutes: 18, lessons: [
    ["processor", "Create the AprilTagProcessor", "The processor analyzes frames. Set output units explicitly so telemetry is unambiguous."],
    ["portal", "Build the VisionPortal", "Select Webcam 1, attach aprilTag, then build the portal. addProcessor enables the processor by default."],
    ["wait", "Wait for Start", "The portal may stream during INIT. The detection-reading loop begins after the driver starts the OpMode."],
    ["detections", "Get a list of detections", "getDetections returns the available detections. A repeated read need not be a new frame; getFreshDetections can signal freshness."],
    ["id", "Select your target", "Filter by ID explicitly. A desired ID of -1 is a convention in the supplied advanced sample for accepting any known tag."],
    ["metadata", "Guard the pose access", "Unknown tags can have decoded IDs without metadata. Check the required fields before reading a pose."],
    ["pose", "Print range and bearing", "This example requests inches and degrees. Range is planar distance from the camera, and bearing is positive left."],
    ["telemetry", "Update the Driver Station", "Send a useful no-target message as well as valid values. Telemetry should explain why a controller cannot act."],
    ["close", "Close the portal", "finally releases the camera when the OpMode exits. This differs from merely hiding the preview."],
    ["tank", "Read the supplied drive-to-tag sample", "Trace targetFound, desiredTag, rangeError, headingError, clipping, left-bumper override, and motor mixing in the full FIRST sample."],
  ].map(([focus, title, subtitle]) => slide("web-code-" + focus, title, subtitle, ["Follow the code segments, then compare the equivalent Limelight concept.", "The examples are Java. Copy complete files with imports, not just the highlighted lines."], subtitle, focus === "tank" ? "tank" : "init", "code", "webcam:" + focus)) },
  { id: "control", label: "08", title: "Turn vision into motion", description: "Error, gain, limits, and override", path: "shared", minutes: 20, lessons: [
    slide("control-loop", "Turn a measurement into an error.", "Decide what value should become zero.", ["Centering: headingError = bearing for VisionPortal. For this CCW-positive tank mixer, use -tx from Limelight.", "Approaching: rangeError = measuredRange - desiredDistance.", "Distance must come from a verified pose or geometry model; tx alone does not provide range."], "Our turn convention is positive counterclockwise.", "tank", "axes"),
    slide("gain", "Small corrections, repeated.", "A proportional controller scales the error.", ["turn = headingError × TURN_GAIN.", "A small gain responds slowly; a large gain can overshoot or oscillate with delay.", "Use the live lab to compare gain values while keeping the same starting pose."], "Try gain 0.01, then 0.06. Watch both error and command.", "tank", "challenge", "gain"),
    slide("limit", "Bound what the controller can ask for.", "Clipping and tolerance serve different purposes.", ["Range.clip limits output to a chosen maximum magnitude.", "A deadband sets output to zero when the error is already small enough.", "Motor mixing can exceed ±1 even after individual axes are clipped; normalize the pair."], "A command limit is not a tolerance, and neither replaces driver override.", "tank", "code", "control:limit"),
    slide("override", "The driver stays in control.", "Enable assistance deliberately, and release it immediately.", ["The supplied sample uses left_bumper && targetFound to enable automatic movement.", "Otherwise it returns to reduced-power manual joystick control.", "This lab zeros automatic commands on invalid or stale targets, Stop, or release of Hold assist."], "Hold assist in the lab; release it to stop automatic motion.", "tank", "challenge", "assist"),
    slide("tank-mixing", "Mix forward and turning commands.", "The pasted example uses a two-wheel tank drivetrain.", ["leftPower = drive - turn; rightPower = drive + turn.", "Positive turn is counterclockwise after motor directions are configured so positive powers move forward.", "If the maximum absolute wheel power exceeds 1, divide both by that maximum. Mecanum needs its own four-wheel mixer."], "Verify motor directions on hardware before any autonomous test.", "tank", "code", "control:mix"),
    slide("align-challenge", "Challenge: center the tag.", "Use a bounded controller to bring the heading error within 2°.", ["Start the camera and hold assist with control mode set to Align.", "Tune the gain and maximum turn to reduce the error smoothly.", "Completion requires a valid tag, a heading error within 2°, and bounded commands."], "A centered target should not require a nonzero turn command.", "tank", "challenge", "align"),
    slide("approach-challenge", "Challenge: stop at 12 inches.", "Combine heading and range corrections.", ["Select Approach in the lab and hold assist.", "Keep gain, tolerance, and maximum output sensible. The lab uses its explicit geometric range model.", "Completion requires valid target data, heading within 2°, and range within 1 inch of 12."], "On a physical Limelight robot, replace the lab's range model with a validated measurement.", "tank", "challenge", "approach"),
    quiz("control-check", "Spot the sign error", "The tag is to the right, so Limelight tx is positive. With a positive-CCW tank mixer, which turn command points toward it?", ["Positive tx × gain", "Negative tx × gain", "Tag ID × gain"], 1, "A right turn is clockwise. In this mixer that is a negative turn command.", "tank"),
  ] },
  { id: "troubleshoot", label: "09", title: "Test & troubleshoot", description: "Find the fault before turning a wheel", path: "shared", minutes: 12, lessons: [
    slide("bench", "Start with telemetry, then motors.", "Test the complete data chain in a controlled sequence.", ["Verify wiring, configuration name, pipeline type, family, measured size, and filter.", "Move a known tag right, left, nearer, and farther. Verify units and signs.", "Only then enable bounded assistance, with an immediate driver override and a clear test area."], "A successful detection does not prove your control sign is correct.", "tank", "checklist"),
    slide("no-detection", "Why is there no target?", "Follow the first failing link in the chain.", ["Is the camera connected and streaming?", "Does the pipeline match the tag family, and does the filter admit its ID?", "Can you see a clear, sufficiently large tag inside the processed image region?"], "Use the troubleshooting tool to choose a symptom and get the next concrete check.", "tracking", "troubleshoot", "detection"),
    slide("bad-pose", "Why does the pose jump?", "Separate recognition problems from geometric errors.", ["Confirm physical tag size and calibration for the selected camera resolution.", "Inspect blur, glare, viewing angle, and camera mounting rigidity.", "Check map season, units, field origin, and camera-to-robot transform before trusting a field pose."], "An incorrect constant offset often points to a transform or map error.", "intro", "troubleshoot", "pose"),
    slide("wrong-turn", "Why does it turn away?", "Verify signs with motors disabled.", ["Make both wheels move forward for positive drive power.", "Check that positive turn is counterclockwise for your mixer.", "Use bearing for VisionPortal; use -tx for this Limelight/mixer combination. Do not substitute yaw."], "Change one convention at a time and retest with a known target direction.", "tank", "troubleshoot", "turn"),
    slide("fault-challenge", "Recover from a lost target.", "A safe automatic command becomes zero when vision cannot be used.", ["Start assistance, then enable the Drop frames fault.", "Observe invalid frames and zero motor commands.", "Try latency, noise, a wrong family, and an excluded ID. Explain each behavior."], "Challenge: trigger an invalid result and verify the drive and turn commands are zero.", "tank", "challenge", "fault"),
    quiz("final-check", "Final practical check", "A result was valid 800 ms ago, but the robot has moved. What should the controller do?", ["Continue using it until another tag appears", "Reject stale data and return to its defined fallback", "Increase gain to catch up"], 1, "Freshness is separate from validity. Define a timeout and stop assistance or return to driver control when measurements are too old.", "java"),
  ] },
  { id: "finish", label: "10", title: "Take it to the robot", description: "Examples, checklist, and references", path: "shared", minutes: 6, lessons: [
    slide("recap", "You now know the whole chain.", "Choose a camera, validate its measurements, and act deliberately.", ["AprilTag identity is separate from its size, metadata, and pose.", "VisionPortal manages webcam processing; Limelight runs its own pipelines.", "A controller needs a selected target, correct frame, known units, fresh data, limits, and override."], "Explain each link to another staff member before moving to hardware.", "portal", "compare"),
    slide("field-checklist", "Your field-side checklist.", "Print this before a physical workshop.", ["Mount and cable secure; active Robot Configuration names match code.", "Family, printed size, pipeline, filter, calibration, and field map verified.", "Exposure and gain tested in venue light; signs and units verified in telemetry.", "Output limits, lost-target fallback, Stop, and driver override tested."], "Repeat checks after a camera move, OS update, or field-map change.", "tank", "checklist"),
    slide("downloads", "Start with an example you understand.", "Download full Java files and adapt the hardware names for your robot.", ["Limelight: device setup, pipeline selection, result checks, fiducial IDs, and telemetry.", "Webcam: processor and portal setup, tag selection, pose checks, and cleanup.", "Advanced: the user-supplied FIRST tank drive-to-AprilTag sample, including its original license."], "Examples target the repo's FTC SDK 11.2.1 reference. Hardware compilation and driving validation remain a separate physical test.", "tank", "resources"),
    slide("references", "Keep the official references close.", "Go deeper without guessing from a screenshot.", ["Check the exact SDK and LimelightOS versions used by your team.", "Advanced extension: MegaTag2 orientation fusion, localization, camera calibration, and multi-camera resource management.", "Facilitator prompt: when is simple tag centering enough, and when does the task require field localization?"], "Use the source link on every lesson to trace its technical guidance.", "java", "resources"),
  ] },
];
export const allLessons = modules.flatMap(m => m.lessons);
const workshopLesson = (id: string, changes: Partial<Lesson> = {}): Lesson => ({ ...allLessons.find(l => l.id === id)!, ...changes });
export const workshopModules: Module[] = [
  { id: "welcome", label: "01", title: "The essentials", description: "What tags and camera software do", path: "shared", minutes: 2, lessons: [
    workshopLesson("welcome", { title: "From camera to code in 30 minutes.", subtitle: "A practical FTC staff workshop: configure Limelight, understand the target data and Java, and try it in the simulator.", points: ["An AprilTag is a recognizable pattern with a numeric ID. Software uses its measured size and camera calibration to estimate pose.", "Today: 2 minutes of essentials, 3 of setup, 6 in LimelightOS, 5 reading target values, 7 reading code, 5 experimenting, and 2 to wrap up."], takeaway: "Our goal: one reliable tag result, data you understand, code you can explain, and a visible effect in the lab.", note: "0–2 min: keep introductions brief. Point out the encoded ID and black border, then compare the two processing paths. The reference library is optional follow-up reading." }),
    workshopLesson("compare", { points: ["Webcam: VisionPortal opens the camera and sends frames to AprilTagProcessor on the Control Hub.", "Limelight: the camera runs the AprilTag pipeline; the robot reads results through Limelight3A."], takeaway: "VisionPortal manages the webcam stream. Limelight processes on the camera. Both need valid results before acting.", note: "Spend about 90 seconds on this comparison. Explain VisionPortal's purpose; save detailed webcam settings for the reference library." }),
  ] },
  { id: "workshop-setup", label: "02", title: "Connect & configure", description: "Hardware name and browser setup", path: "limelight", minutes: 3, lessons: [
    workshopLesson("ll-hardware", { title: "Connect it. Name it limelight.", points: ["Use a USB-C to USB-A data cable and the Control Hub's blue USB 3.0 port. It is the recommended and officially supported Limelight 3A connection.", "Avoid USB 2.0 for competition use. One reason is its documented ESD vulnerability and shared bus with the Control Hub's internal Wi-Fi radio.", "In Driver Station: Configure Robot → Scan → Ethernet Device. Name it limelight, then save and activate the configuration. That exact name is what hardwareMap.get uses."], note: "2–4 min: recommend the blue USB 3.0 port. Explain that USB 2.0 shares the Wi-Fi bus and an ESD event can disconnect the Driver Hub." }),
    workshopLesson("ll-interface", { note: "4–5 min: show where to open LimelightOS. Use the approved reference images in the next module; avoid OS update and localization detours." }),
  ] },
  { id: "workshop-ui", label: "03", title: "LimelightOS essentials", description: "Pipeline, family, image, and ID", path: "limelight", minutes: 6, lessons: [
    workshopLesson("ui-pipeline", { title: "Choose a pipeline, then AprilTags.", subtitle: "A pipeline is one saved set of camera and detection settings that Limelight runs on each image. Its slot number in LimelightOS must match pipelineSwitch in Java.", note: "5–7 min: use Pipeline index and Pipeline type below. Explain that pipeline 0 is a saved configuration slot, not tag ID 0." }),
    workshopLesson("ui-family", { title: "Match the family and measured size.", subtitle: "Use 36h11 for the workshop tags. Measure the black border; size controls the pose scale.", note: "7–9 min: select Tag family, then Marker size in the interactive control list. This practice model uses 50.8 mm, not a universal season value." }),
    workshopLesson("ui-exposure", { title: "Make the tag clear in the image.", subtitle: "Motion blur is the smear created while the robot, camera, or tag moves during an exposure. It softens tag corners and can cause missed detections or an unstable pose.", note: "9–10 min: change exposure, then gain. Explain that higher resolution may retain more edge detail when blur is mild, but only a shorter exposure directly reduces motion blur. Show a poor exposure result and recover." }),
    workshopLesson("ui-filter", { title: "Choose which tag the robot should use.", subtitle: "An ID filter can exclude a tag even while it remains visible in the image.", note: "10–11 min: enter 20 in ID filters. Distinguish tag ID from pipeline index. Leave crop and sort at their defaults." }),
  ] },
  { id: "workshop-data", label: "04", title: "Understand target data", description: "Angles, area, identity, and pose", path: "shared", minutes: 5, lessons: [
    { ...slide("workshop-limelight-values", "What does Limelight return?", "Read tx, ty, ta, tag ID, validity, freshness, and latency with their units and limits.", [], "tx and ty are angles. ta is image area. None of them is physical distance by itself.", "java", "measurements", "limelight"), note: "11–13 min: connect each value to what participants see in the camera view. Emphasize units and that tx, ty, and ta do not directly give physical distance." },
    { ...slide("workshop-processor-values", "What does AprilTagProcessor return?", "Read identity, pixels, metadata, camera-relative position, range, bearing, elevation, and tag rotation.", [], "For basic driving, ID tells you which tag, bearing points toward it, range estimates distance, and yaw describes the tag face.", "pose", "measurements", "webcam"), note: "13–16 min: distinguish pixel center from pose values. Use ID, range, bearing, and yaw as the practical subset; mention the FTC camera-coordinate axes before x, y, and z." },
  ] },
  { id: "workshop-code", label: "05", title: "Explain the Java", description: "Initialize, validate, read, compare", path: "shared", minutes: 7, lessons: [
    workshopLesson("ll-code-hardware", { title: "Get the camera. Select the pipeline. Start.", subtitle: "Trace Limelight3A → hardwareMap.get → pipelineSwitch → start → waitForStart.", points: [], note: "16–18 min: use Next step to explain the object, exact configured name, saved pipeline slot, and start. Show in lab mirrors the selected operation." }),
    workshopLesson("ll-code-result", { title: "Ask for a result, then check it.", subtitle: "getLatestResult asks Limelight for its newest detection data. Check that the result exists and is valid before using its measurements.", points: [], note: "18–20 min: explain that result is a variable holding the returned data. It can be null, and another call can describe the same camera image. Then explain the validity check." }),
    workshopLesson("ll-code-tx", { title: "tx is an angle. Telemetry makes it visible.", subtitle: "getTx reports horizontal offset in degrees: positive right, negative left, near zero when centered on the crosshair.", takeaway: "tx is an angle, not distance. Use telemetry.update to show the value on the Driver Station.", points: [], note: "20–21 min: highlight getTx and telemetry.update. Predict what happens when the tag moves right. tx alone is not distance. The simulator exercises follow next." }),
    workshopLesson("web-code-processor", { title: "The webcam equivalent: processor + portal.", subtitle: "AprilTagProcessor analyzes the image; VisionPortal connects it to the webcam and manages the stream.", points: [], note: "21–23 min: show processor and portal creation, then jump to pose. Compare ftcPose.bearing (+ left) with Limelight tx (+ right). Avoid walking the whole tank sample today." }),
  ] },
  { id: "workshop-lab", label: "06", title: "Try it in the simulator", description: "See angles, center, lose the target", path: "limelight", minutes: 5, lessons: [
    workshopLesson("align-challenge", { title: "Move the tag. Predict the angle.", subtitle: "Run the camera, move the robot or tag, and watch tx change. Bring it near zero.", focus: "angles", points: ["Open the lab and select Run OpMode. Use the Field tab to drag a tag or change the robot heading.", "Move the target right and left, then center it. Check that the magnitude of tx falls within 2°."], note: "23–25 min: ask participants to predict the sign before moving the tag. Check the result when centered." }),
    workshopLesson("override", { title: "Let a small turn correct the error.", subtitle: "In Control, hold assist to center the tag. Release it and watch the automatic commands return to zero.", points: ["Move the robot heading away from center. In Control, keep mode Align and start with turn gain 0.01.", "Hold assist. This CCW-positive tank mixer uses turn = -tx × gain, with a maximum turn limit.", "Release assist and verify the drive and turn outputs are zero."], note: "25–27 min: demonstrate one bounded correction and release. Approach and advanced tuning are optional after the workshop." }),
    workshopLesson("fault-challenge", { title: "Lose the target. Stop the correction.", subtitle: "A robot needs a defined fallback when camera data cannot be used.", points: ["While the camera is running, move the tag out of view or select the wrong tag family.", "In Control, hold assist and inspect the invalid result: automatic drive and turn must remain zero.", "Restore the tag or family and confirm detection returns."], note: "27–28 min: demonstrate one failure, zero commands, and recovery. Do not try every optional fault setting." }),
  ] },
  { id: "workshop-finish", label: "07", title: "Take it to the robot", description: "Examples and the final check", path: "shared", minutes: 2, lessons: [
    workshopLesson("downloads", { title: "Keep the code. Repeat the three checks.", subtitle: "Correct setup → valid measurement → bounded command with a fallback.", points: ["Names and pipeline match. The tag family, measured size, and image are correct.", "Telemetry signs make sense; missing or stale data disables assistance.", "Verify motor direction, limits, and driver override on your actual robot."], note: "28–30 min: download the examples, recap the three checks, and take questions. The reference library has the longer lessons and printable checklist." }),
  ] },
];
export function courseFor(path: Path, mode: "workshop" | "reference" = "reference") { return mode === "workshop" ? workshopModules : modules.filter(m => path === "both" || m.path === "shared" || m.path === path); }
