import limelight from "../../public/examples/LimelightWorkshop.java?raw";
import webcam from "../../public/examples/WebcamWorkshop.java?raw";
import tank from "../../public/examples/RobotAutoDriveToAprilTagTank.java?raw";
import align from "../../public/examples/LimelightAlignTank.java?raw";
import quick from "../../public/examples/AprilTagWorkshop.java?raw";
import mecanum from "../../public/examples/MecanumAimAssistLimelight.java?raw";
export type Segment = { id: string; title: string; start: string; count: number; explanation: string; effect: string; details?: string[] };
export type Example = { file: string; source: string; segments: Segment[] };
const segment = (id: string, title: string, start: string, count: number, explanation: string, effect = id, details?: string[]): Segment => ({ id, title, start, count, explanation, effect, details });
export const examples: Record<string, Example> = {
  mecanum: { file: "MecanumAimAssistLimelight.java", source: mecanum, segments: [
    segment("constants", "Name every tuning decision", "private static final int BLUE_GOAL_ID", 6, "The accepted tag IDs, proportional gain, maximum automatic turn, driver-override threshold, and centering tolerance are constants. Keeping them together makes field tuning deliberate and reviewable."),
    segment("hardware", "Initialize the drive and camera", "initDrive();", 6, "Initialize all four drive motors, retrieve the Limelight by its exact Robot Configuration name, ask for results 30 times per second, select saved pipeline slot 0, and start receiving camera results. Pipeline 0 is a slot, not a tag ID.", "hardware"),
    segment("wait", "Show readiness, then wait", "telemetry.addLine(\"Ready", 3, "Telemetry confirms initialization reached this point. waitForStart pauses until the Driver Station starts the OpMode; the camera was started during INIT."),
    segment("inputs", "Read the driver every loop", "double drive =", 5, "The left stick supplies forward and strafe motion; the right stick supplies manual rotation. calculateAssistTurn may add a small correction, and clip keeps the combined turn inside the legal motor-power range."),
    segment("cleanup", "Stop safely on every exit", "} finally {", 4, "finally runs whether the loop ends normally or because of an error. It stops every drive motor and tells the robot to stop requesting Limelight results.", "stop"),
    segment("override", "Driver input always wins", "if (!assistEnabled", 1, "Return zero automatic turn when assist is off or the driver is already turning past the deadzone. This prevents aim assist from fighting an intentional command.", "assist"),
    segment("valid", "Reject missing or invalid data", "LLResult result =", 2, "Ask for the latest result, then require both a non-null object and a valid target before reading detections. A production robot should also define a freshness limit."),
    segment("select", "Select the actual goal tag", "LLResultTypes.FiducialResult target", 8, "Search the per-tag fiducial list for ID 20 or 24 and keep that exact object. This avoids mixing one tag's ID with another target's primary tx value."),
    segment("error", "Calculate one angular error", "double tx =", 5, "Read tx from the selected fiducial, subtract the desired crosshair offset, and show both ID and error in telemetry. The error is an angle in degrees, not sideways distance."),
    segment("bounded", "Apply tolerance, gain, and limit", "if (Math.abs(error)", 2, "Inside the 1° tolerance, command zero. Outside it, multiply error by the turn gain and clip the result to ±0.20. If your verified drivetrain sign is opposite, invert this correction once."),
    segment("toggle", "Toggle only once per button press", "boolean currentA", 3, "Rising-edge detection changes assistEnabled only when A changes from released to pressed. Holding A does not toggle the mode repeatedly."),
    segment("mix", "Mix and normalize mecanum power", "double lf =", 12, "Combine drive, strafe, and turn for four mecanum wheels. Divide every wheel by the same scale when any magnitude exceeds 1, preserving the requested direction while keeping power bounded."),
  ] },
  quick: { file: "AprilTagWorkshop.java", source: quick, segments: [
    segment("hardware", "Get a configured device", "Limelight3A limelight =", 2, "Limelight3A is the device class. limelight is our variable. hardwareMap.get finds the device named limelight in the active Robot Configuration. Names must match exactly."),
    segment("pipeline", "Choose the saved pipeline", "limelight.pipelineSwitch", 1, "Select slot 0, which you already configured as an AprilTag pipeline in LimelightOS. This number is not the tag ID."),
    segment("start", "Start reading camera results", "limelight.start", 1, "This tells the FTC camera software to repeatedly ask Limelight for its newest result. The camera processes the image; the robot receives the measurements."),
    segment("wait", "Wait for the driver to press Start", "waitForStart", 1, "The initialization above happens first. This line waits for the Driver Station Start button before the loop continues."),
    segment("loop", "Repeat until Stop", "while (opModeIsActive", 1, "Each loop reads the latest available result and updates telemetry. Pressing Stop ends the loop."),
    segment("result", "Ask for the newest result", "LLResult result =", 1, "getLatestResult asks Limelight for its newest detection data. The variable named result holds that data during this loop. Sometimes there is no result, so the value can be null. Calling it again can return data from the same camera image."),
    segment("valid", "Check before using", "if (result != null", 1, "First check that an object exists. Then isValid checks whether the pipeline has a valid target. The && operator avoids calling a method on null."),
    segment("tx", "Read the horizontal angle", 'telemetry.addData("tx', 1, "getTx returns horizontal crosshair offset in degrees: positive right, negative left. Zero means centered on the crosshair. It is an angle, not a physical distance."),
    segment("telemetry", "Show it on the Driver Station", "telemetry.update", 2, "addData stages the value. update sends it to the Driver Station. sleep gives a short pause between loop iterations."),
    segment("stop", "Stop requesting results when finished", "} finally {", 3, "finally tells the robot to stop requesting Limelight results even if the code exits unexpectedly. This example only displays telemetry; motor control additionally needs a desired ID, freshness, limits, and override.", "stop"),
  ] },
  align: { file: "LimelightAlignTank.java", source: align, segments: [
    segment("id", "Choose the per-tag result", "LLResultTypes.FiducialResult desired", 11, "Check received-result age, pipeline index, and ID. The matched tag supplies the actual control angle; primary tx may belong to another tag.", "result"),
    segment("sign", "Turn toward the target", "double tx =", 4, "Positive tx is right. This mixer is positive CCW, so use -tx. Stop turning inside the 2° tolerance and clip output to ±0.25.", "align"),
    segment("override", "Driver override and target loss", "if (gamepad1.left_bumper)", 13, "Hold the bumper to align. If the target disappears while held, automatic commands remain zero. Release the bumper to return to manual control.", "assist"),
    segment("mix", "Normalize wheel powers", "double leftPower =", 5, "Combine forward and turn, then scale both wheel powers together to stay inside ±1.", "align"),
    segment("stop", "Stop motors and camera updates", "} finally {", 5, "Always set both motor powers to zero and stop requesting camera results when leaving the OpMode.", "stop"),
  ] },
  limelight: { file: "LimelightWorkshop.java", source: limelight, segments: [
    segment("hardware", "Get a configured device", "Limelight3A limelight =", 2, "Limelight3A names the class. limelight holds a reference to the device. hardwareMap.get takes its type and exact Robot Configuration name."),
    segment("poll", "Request results; publish telemetry", "limelight.setPollRateHz", 2, "Poll at 100 requests per second; publish telemetry every 100 ms. These independent cadences do not change the camera frame rate."),
    segment("pipeline", "Switch to slot 0", "limelight.pipelineSwitch", 1, "This requests a saved pipeline asynchronously. The result's pipeline index is checked later; slot 0 is not inherently an AprilTag pipeline."),
    segment("start", "Start receiving results", "limelight.start", 1, "This makes the FTC camera software repeatedly request the newest result from Limelight. It does not press the Driver Station Start button."),
    segment("wait", "Wait for the driver", "waitForStart", 1, "Initialization is complete. The OpMode waits until Start is pressed."),
    segment("loop", "Run until Stop", "while (opModeIsActive", 1, "Run a short loop repeatedly. Stop ends this loop, then finally releases the device."),
    segment("result", "Ask for the newest result", "LLResult result =", 1, "getLatestResult asks Limelight for its newest detection data. The variable named result holds that data during this loop. Sometimes there is no result, so the value can be null. Calling it again can return data from the same camera image."),
    segment("valid", "Check before using", "if (result != null", 3, "Short-circuit && protects isValid() from null. Also verify pipeline index and age. getStaleness is age since receipt on the Control Hub, not full image age."),
    segment("tx", "Read values with units", 'telemetry.addData("Primary tx', 7, "tx/ty are crosshair-relative angles in degrees. ta is image coverage in percent. Capture and targeting latency are separate values in milliseconds."),
    segment("fiducials", "Inspect each tag", "for (LLResultTypes.FiducialResult", 6, "Each fiducial result has its own ID and angle. Use a matching tag's value when selecting an ID; parent tx may refer to another target."),
    segment("telemetry", "Send the telemetry", "telemetry.update", 2, "addData stages values; update publishes them. sleep briefly yields time between iterations."),
    segment("stop", "Clean up on every exit", "} finally {", 3, "finally runs even when an exception or early exit leaves the try block. stop() ends the repeated Limelight result requests.", "stop"),
  ] },
  webcam: { file: "WebcamWorkshop.java", source: webcam, segments: [
    segment("processor", "Build the same AprilTag processor", "aprilTag = new AprilTagProcessor.Builder", 2, "Builder().build() creates the processor that finds AprilTags.\nDecimation reduces image detail for the tag search: fewer pixels can mean faster detection.\nsetDecimation(2) is a middle ground between detection speed and seeing distant tags.\nLower value (1): more detail; small or distant tags can be easier to detect, but processing may be slower.\nHigher value (3): less detail; detection can be faster, but small or distant tags may disappear.\nTry 2 first. If distant tags are missed, compare with 1. Check detection reliability and frame rate using your camera.", "processor", ["aprilTag is a variable. It will remember the processor object so other methods can use it.", "new AprilTagProcessor.Builder() creates a helper used to configure the processor.", ".build() finishes the configuration and returns the new AprilTagProcessor.", ".setDecimation(2) tells the processor to reduce the image before searching. This can run faster, but distant tags may become harder to see."]),
    segment("portal", "Attach the processor to Webcam 1", "visionPortal = new VisionPortal.Builder", 4, "These chained method calls choose the camera, connect the AprilTag processor, and start building the camera system.", "portal", ["visionPortal is the variable that will manage the camera and its processors.", "new VisionPortal.Builder() starts a camera configuration.", "hardwareMap.get(WebcamName.class, \"Webcam 1\") asks Robot Configuration for a webcam with that exact name.", ".addProcessor(aprilTag) sends each camera frame to the processor created above.", ".build() opens the camera system and returns the finished VisionPortal."]),
    segment("wait", "Initialize before Start", "initAprilTag();", 5, "This block prepares the camera, writes a ready message, and then waits for the driver.", "wait", ["initAprilTag(); calls the helper method defined near the bottom of the file.", "telemetry.addLine(...) prepares a message for the Driver Station.", "telemetry.update(); actually sends the prepared message.", "waitForStart(); pauses here until Start is pressed. Code after it does not run during INIT."]),
    segment("detections", "Read the current detection list", "List<AprilTagDetection> currentDetections", 2, "The processor may see zero, one, or several tags, so the results are stored in a list and checked one at a time.", "detections", ["List<AprilTagDetection> means a list whose items are AprilTagDetection objects.", "currentDetections is the name given to that list for this method call.", "aprilTag.getDetections() asks the processor for its current results.", "for (... detection : currentDetections) repeats the following block once for every detection in the list."]),
    segment("metadata", "Require a tag from the library", "if (detection.metadata == null)", 4, "This condition rejects a decoded tag when the program does not know its physical information.", "metadata", ["if (...) runs its block only when the condition inside the parentheses is true.", "detection.metadata is the library information connected to this tag, including its known name and size.", "== null means that no metadata object exists.", "continue; skips the rest of this loop iteration and moves to the next detected tag."]),
    segment("id", "Return the first matching tag", "if (DESIRED_TAG_ID < 0", 5, "This condition accepts any known tag when the desired ID is -1, or accepts only the exact requested ID.", "id", ["DESIRED_TAG_ID < 0 is true when the constant is -1, which means any known tag is allowed.", "|| means OR. Only one side must be true.", "detection.id == DESIRED_TAG_ID compares the detected number with the requested number.", "return detection; immediately ends findDesiredTag() and gives the selected detection back to runOpMode().", "return null; at the end means no usable tag was found."]),
    segment("pose", "Display the selected tag's pose", 'telemetry.addData("Found"', 5, "Each telemetry line reads a value from the same selected detection and labels it for the driver.", "pose", ["desiredTag.id is the number encoded in the tag.", "desiredTag.metadata.name is the name stored in the tag library.", "desiredTag.ftcPose.range is the camera-to-tag distance in inches.", "desiredTag.ftcPose.bearing is the left/right direction to the tag center in degrees.", "desiredTag.ftcPose.yaw is the tag face's rotation, not the direction used to point toward its center."]),
    segment("telemetry", "Explain when no target is usable", "} else {", 6, "The else block handles the no-target case, and the last two calls finish one pass through the loop.", "telemetry", ["else runs when desiredTag != null was false, meaning findDesiredTag() returned null.", "telemetry.addLine(...) prepares the no-target message.", "telemetry.update(); sends all prepared values to the Driver Station together.", "sleep(20); pauses for 20 milliseconds so the loop does not run continuously without yielding."]),
    segment("close", "Close the camera", "} finally {", 3, "This cleanup block releases the camera whenever the try block ends.", "stop", ["try marks the code that uses the camera.", "finally runs after try even if the OpMode stops because of an error.", "visionPortal.close(); stops streaming and releases the webcam so another OpMode can use it."]),
  ] },
  control: { file: "RobotAutoDriveToAprilTagTank.java", source: tank, segments: [
    segment("constants", "Set the controller goals and limits", "final double DESIRED_DISTANCE", 11, "DESIRED_DISTANCE: how far from the tag to stop, in inches.\nMore distance error → more drive power. Near the goal → less power. At the goal → zero. Too close → reverse.\nSPEED_GAIN = 0.02: 10 inches too far × 0.02 = 0.20 drive power.\nTURN_GAIN = 0.01: 10° off-center × 0.01 = 0.10 turn power. Centered → zero turn.\nPower limits: drive up to 0.50; turn up to 0.25."),
    segment("devices", "Choose the camera and tag", "private static final boolean USE_WEBCAM", 6, "USE_WEBCAM selects a configured webcam instead of the phone's back camera. DESIRED_TAG_ID chooses one tag, while -1 accepts any known tag. VisionPortal owns the camera and AprilTagProcessor analyzes its frames.", "processor"),
    segment("motors", "Map and orient both motors", "leftDrive  = hardwareMap.get", 9, "The strings left_drive and right_drive must match Robot Configuration. One motor is reversed so equal positive power moves both physical wheels forward."),
    segment("target", "Find a known desired tag", "List<AprilTagDetection> currentDetections", 22, "Read the current detection list, require metadata so physical pose is available, match the requested ID, and keep the first usable detection. Telemetry explains skipped and unknown tags.", "result"),
    segment("telemetry", "Show range and bearing", "if (targetFound)", 9, "When a target is found, display its ID, library name, range in inches, and bearing in degrees. Otherwise tell the driver to search manually. Bearing—not tag yaw—is the centering error."),
    segment("limit", "Convert error into bounded power", "double  rangeError", 8, "Range error is measured range minus desired range. Heading error is the tag bearing. Multiply each error by its gain, then clip drive and turn separately to the configured maximums.", "align"),
    segment("override", "Hold the bumper for automatic help", "if (gamepad1.left_bumper", 19, "Automatic drive runs only while the left bumper is held and a valid target exists. Releasing the bumper or losing the target immediately returns to reduced manual joystick control.", "assist"),
    segment("mix", "Understand x and yaw in moveRobot", "double leftPower", 14, "Here, x and yaw are requested robot movements. They are not the AprilTag's ftcPose.x position or ftcPose.yaw orientation. runOpMode calls moveRobot(drive, turn), so x receives drive power and yaw receives turn power.", "align", ["x is forward/reverse power: positive moves forward, negative moves backward, and 0 asks for no forward motion.", "yaw is turning power: positive requests a counterclockwise turn, negative requests clockwise, and 0 asks the robot to drive straight.", "leftPower = x - yaw slows or reverses the left wheel during a positive turn.", "rightPower = x + yaw speeds up the right wheel during a positive turn.", "If either calculated power is larger than 1, both values are divided by the same max value. This keeps them legal without changing the movement ratio.", "leftDrive.setPower(...) and rightDrive.setPower(...) finally send the calculated commands to the motors."]),
    segment("processor", "Build the AprilTag processor", "aprilTag = new AprilTagProcessor.Builder", 12, "The processor detects AprilTags. Decimation 2 is a sample tradeoff: fewer pixels can process faster but generally shorten detection range. Validate this setting with your own camera and tags.", "processor"),
    segment("portal", "Attach the selected camera", "if (USE_WEBCAM)", 11, "VisionPortal.Builder selects Webcam 1 or the phone's back camera, attaches the AprilTag processor, and opens the vision pipeline when build() runs.", "portal"),
    segment("exposure", "Wait until the webcam is streaming", "if (visionPortal.getCameraState()", 10, "Camera startup is asynchronous. Wait for STREAMING while still honoring a Stop request; camera controls may not be ready before this state.", "portal"),
    segment("gain", "Set exposure and gain", "ExposureControl exposureControl =", 11, "Switch supported webcam controls to manual mode, set exposure in milliseconds, then set gain. Short exposure reduces motion blur; gain brightens the image but can add noise. Tune both on the actual camera.", "exposure"),
  ] },
};
export function segmentLines(example: Example, s: Segment) {
  const start = example.source.split("\n").findIndex(line => line.includes(s.start));
  return { start, end: start + s.count - 1 };
}


